#!/bin/bash

# Configuration
# Set these as secrets in GitHub: DISCORD_WEBHOOK_URL
export REPO_NAME="${GITHUB_REPOSITORY:-manifestautomations/manifest-agency}"

echo "📢 Generating Weekly Digest for $REPO_NAME..."

# Check dependencies
if ! command -v gh &> /dev/null; then
    echo "❌ Error: GitHub CLI (gh) is not installed."
    exit 1
fi
if ! command -v python3 &> /dev/null; then
    echo "❌ Error: Python 3 is not installed."
    exit 1
fi

# Check authentication
if ! gh auth status &> /dev/null; then
    echo "⚠️  Warning: GitHub CLI not authenticated. Attempting to run anyway (might fail)..."
fi

# Get Open Issues
ISSUES=$(gh issue list --repo "$REPO_NAME" --limit 5 --json number,title,author,url --template \
  '{{range .}}- [{{.title}}]({{.url}}) (@{{.author.login}})\n{{end}}')

# Get Open PRs
PRS=$(gh pr list --repo "$REPO_NAME" --limit 5 --json number,title,author,url --template \
  '{{range .}}- [{{.title}}]({{.url}}) (@{{.author.login}})\n{{end}}')

# Count totals
# Use wc -l and strip whitespace
export ISSUE_COUNT=$(gh issue list --repo "$REPO_NAME" --state open --limit 1000 --json number | grep -o "number" | wc -l | xargs)
export PR_COUNT=$(gh pr list --repo "$REPO_NAME" --state open --limit 1000 --json number | grep -o "number" | wc -l | xargs)

export TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [ -z "$ISSUES" ]; then ISSUES="No open issues!"; fi
if [ -z "$PRS" ]; then PRS="No open PRs!"; fi

# Prepare JSON payload safely using Python
python3 -c "
import json
import sys
import os

repo_name = os.environ.get('REPO_NAME', 'Unknown Repo')
issue_count = os.environ.get('ISSUE_COUNT', '0')
pr_count = os.environ.get('PR_COUNT', '0')
issues = sys.argv[1]
prs = sys.argv[2]
timestamp = os.environ.get('TIMESTAMP', '')

payload = {
  'embeds': [
    {
      'title': 'Weekly Engineering Digest 🛠️',
      'description': f'Here is the status of **{repo_name}** this week.',
      'color': 5814783,
      'fields': [
        {
          'name': f'🔥 Open Issues ({issue_count})',
          'value': issues,
          'inline': False
        },
        {
          'name': f'🚀 Open PRs ({pr_count})',
          'value': prs,
          'inline': False
        }
      ],
      'footer': {
        'text': f'Generated by Manifest Automations • {timestamp}'
      }
    }
  ]
}
print(json.dumps(payload))
" "$ISSUES" "$PRS" > payload.json

# Send to Discord
if [ -z "$DISCORD_WEBHOOK_URL" ]; then
  echo "❌ Error: DISCORD_WEBHOOK_URL is not set."
  echo "Payload would be:"
  cat payload.json
  rm payload.json
  exit 1
fi

echo "Sending to Discord..."
curl -H "Content-Type: application/json" \
     -X POST \
     -d @payload.json \
     "$DISCORD_WEBHOOK_URL"

rm payload.json
echo "✅ Done!"
