#!/bin/bash

# Configuration
# Set these as secrets in GitHub: DISCORD_WEBHOOK_URL
REPO_NAME=${GITHUB_REPOSITORY}

echo "📢 Generating Weekly Digest for $REPO_NAME..."

# Get Open Issues
ISSUES=$(gh issue list --limit 5 --json number,title,author,url --template \
  '{{range .}}- [{{.title}}]({{.url}}) (@{{.author.login}})\n{{end}}')

# Get Open PRs
PRS=$(gh pr list --limit 5 --json number,title,author,url --template \
  '{{range .}}- [{{.title}}]({{.url}}) (@{{.author.login}})\n{{end}}')

# Count totals
ISSUE_COUNT=$(gh issue list --state open --limit 1000 | wc -l)
PR_COUNT=$(gh pr list --state open --limit 1000 | wc -l)

# Prepare JSON payload
# Note: Using a simple structure for Discord
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

PAYLOAD=$(cat <<EOF
{
  "embeds": [
    {
      "title": "Weekly Engineering Digest 🛠️",
      "description": "Here is the status of **$REPO_NAME** this week.",
      "color": 5814783,
      "fields": [
        {
          "name": "🔥 Open Issues ($ISSUE_COUNT)",
          "value": "${ISSUES:-No open issues!}",
          "inline": false
        },
        {
          "name": "🚀 Open PRs ($PR_COUNT)",
          "value": "${PRS:-No open PRs!}",
          "inline": false
        }
      ],
      "footer": {
        "text": "Generated by Manifest Automations • $TIMESTAMP"
      }
    }
  ]
}
EOF
)

# Send to Discord
if [ -z "$DISCORD_WEBHOOK_URL" ]; then
  echo "❌ Error: DISCORD_WEBHOOK_URL is not set."
  echo "Payload would be:"
  echo "$PAYLOAD"
  exit 1
fi

echo "Sending to Discord..."
curl -H "Content-Type: application/json" \
     -X POST \
     -d "$PAYLOAD" \
     "$DISCORD_WEBHOOK_URL"

echo "✅ Done!"
